### ISSUE TITLE
Store the user's history in the local storage?

### ISSUE THREAD

**Issue by benjamintd** [benjamintd/ben-maps#27]
This would allow to display, and search through, the user's previously searched locations.

**Comment by SrihariThalla** [comment]
Not except if I am browsing on a public computer. This doesn't concern me but for some people, it is! One way to tackle this is to add an SSO login (even more privacy concerns?)

Let's do this ;) Privacy concerns can be addressed if raised. We are not storing them on servers or sharing with third parties anyway.

Hey, Benjamin!

**Comment by benjamintd** [comment]
It's true that local storage poses a problem with public computers, but this would be solved by private browsing or adding some control to delete history. I would try to avoid any kind of login, and keep everything local. One of the added values of this project is privacy :)


This feature is low priority compared to #25, I'll hold until I find a good way to implement.

**Comment by SrihariThalla** [comment]
That'd be good! If someone has any privacy concerns, they can raise an issue here anyways!!

**Comment by benjamintd** [comment]
Won't fix
