### ISSUE TITLE
Add Mapillary imagery on search?

### ISSUE THREAD

**Issue by benjamintd** [benjamintd/ben-maps#32]
I'm hesitant to add another (paid) API on top of Mapbox, but it would be cool to provide images on searches other that those which have Wikidata tags.

See [how to display](https://github.com/mapillary/mapillary-js) and [how to search](https://www.mapillary.com/developer/api-documentation/#search-images) Mapillary's data.

**Comment by SrihariThalla** [comment]
Costly, but good street view data!
